package com.example.lorebase.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.lorebase.bean.BrowseHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BROWSE_HISTORY".
*/
public class BrowseHistoryDao extends AbstractDao<BrowseHistory, Long> {

    public static final String TABLENAME = "BROWSE_HISTORY";

    /**
     * Properties of entity BrowseHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id_browse = new Property(0, Long.class, "id_browse", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Link = new Property(2, String.class, "link", false, "LINK");
        public final static Property Date = new Property(3, String.class, "date", false, "DATE");
        public final static Property Is_colloct = new Property(4, boolean.class, "is_colloct", false, "IS_COLLOCT");
        public final static Property Latidude = new Property(5, double.class, "latidude", false, "LATIDUDE");
        public final static Property Longitude = new Property(6, double.class, "longitude", false, "LONGITUDE");
        public final static Property Is_out = new Property(7, boolean.class, "is_out", false, "IS_OUT");
        public final static Property Country = new Property(8, String.class, "country", false, "COUNTRY");
        public final static Property Province = new Property(9, String.class, "province", false, "PROVINCE");
        public final static Property City = new Property(10, String.class, "city", false, "CITY");
        public final static Property District = new Property(11, String.class, "district", false, "DISTRICT");
        public final static Property Street = new Property(12, String.class, "street", false, "STREET");
    }


    public BrowseHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public BrowseHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BROWSE_HISTORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id_browse
                "\"TITLE\" TEXT UNIQUE ," + // 1: title
                "\"LINK\" TEXT," + // 2: link
                "\"DATE\" TEXT," + // 3: date
                "\"IS_COLLOCT\" INTEGER NOT NULL ," + // 4: is_colloct
                "\"LATIDUDE\" REAL NOT NULL ," + // 5: latidude
                "\"LONGITUDE\" REAL NOT NULL ," + // 6: longitude
                "\"IS_OUT\" INTEGER NOT NULL ," + // 7: is_out
                "\"COUNTRY\" TEXT," + // 8: country
                "\"PROVINCE\" TEXT," + // 9: province
                "\"CITY\" TEXT," + // 10: city
                "\"DISTRICT\" TEXT," + // 11: district
                "\"STREET\" TEXT);"); // 12: street
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BROWSE_HISTORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BrowseHistory entity) {
        stmt.clearBindings();
 
        Long id_browse = entity.getId_browse();
        if (id_browse != null) {
            stmt.bindLong(1, id_browse);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(3, link);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
        stmt.bindLong(5, entity.getIs_colloct() ? 1L: 0L);
        stmt.bindDouble(6, entity.getLatidude());
        stmt.bindDouble(7, entity.getLongitude());
        stmt.bindLong(8, entity.getIs_out() ? 1L: 0L);
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(9, country);
        }
 
        String province = entity.getProvince();
        if (province != null) {
            stmt.bindString(10, province);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(11, city);
        }
 
        String district = entity.getDistrict();
        if (district != null) {
            stmt.bindString(12, district);
        }
 
        String street = entity.getStreet();
        if (street != null) {
            stmt.bindString(13, street);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BrowseHistory entity) {
        stmt.clearBindings();
 
        Long id_browse = entity.getId_browse();
        if (id_browse != null) {
            stmt.bindLong(1, id_browse);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(3, link);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
        stmt.bindLong(5, entity.getIs_colloct() ? 1L: 0L);
        stmt.bindDouble(6, entity.getLatidude());
        stmt.bindDouble(7, entity.getLongitude());
        stmt.bindLong(8, entity.getIs_out() ? 1L: 0L);
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(9, country);
        }
 
        String province = entity.getProvince();
        if (province != null) {
            stmt.bindString(10, province);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(11, city);
        }
 
        String district = entity.getDistrict();
        if (district != null) {
            stmt.bindString(12, district);
        }
 
        String street = entity.getStreet();
        if (street != null) {
            stmt.bindString(13, street);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BrowseHistory readEntity(Cursor cursor, int offset) {
        BrowseHistory entity = new BrowseHistory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id_browse
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // link
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // date
            cursor.getShort(offset + 4) != 0, // is_colloct
            cursor.getDouble(offset + 5), // latidude
            cursor.getDouble(offset + 6), // longitude
            cursor.getShort(offset + 7) != 0, // is_out
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // country
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // province
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // city
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // district
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // street
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BrowseHistory entity, int offset) {
        entity.setId_browse(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLink(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIs_colloct(cursor.getShort(offset + 4) != 0);
        entity.setLatidude(cursor.getDouble(offset + 5));
        entity.setLongitude(cursor.getDouble(offset + 6));
        entity.setIs_out(cursor.getShort(offset + 7) != 0);
        entity.setCountry(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setProvince(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCity(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setDistrict(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setStreet(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BrowseHistory entity, long rowId) {
        entity.setId_browse(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BrowseHistory entity) {
        if(entity != null) {
            return entity.getId_browse();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BrowseHistory entity) {
        return entity.getId_browse() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
